import { NextRequest } from 'next/server';
import { prisma } from '@/lib/db';

// Streaming needs the Node runtime (not Edge) and no time limit imposed by
// buffering — the connection stays open for as long as the agent is
// reasoning.
export const runtime = 'nodejs';
export const maxDuration = 120;

/**
 * GET /api/agent/run-stream?committeeId=...
 *
 * Proxies the Python agent-service's live Server-Sent-Events stream
 * (agent-service/api/index.py's /api/run/stream) straight through to the
 * browser. This is a passthrough, not a re-implementation — every event the
 * browser receives is exactly what the agent-service emitted, live, as the
 * agent actually reasoned. If no committeeId is given, the first active
 * committee needing attention is used.
 */
export async function GET(req: NextRequest) {
  const baseUrl = process.env.AGENT_SERVICE_URL;
  if (!baseUrl) {
    return new Response(
      `data: ${JSON.stringify({ type: 'error', text: 'AGENT_SERVICE_URL is not configured.' })}\n\ndata: ${JSON.stringify({ type: 'done' })}\n\n`,
      { headers: { 'Content-Type': 'text/event-stream' } },
    );
  }

  const requestedId = req.nextUrl.searchParams.get('committeeId') ?? undefined;

  const committee = await prisma.committee.findFirst({
    where: {
      status: { in: ['active', 'needs_attention'] },
      ...(requestedId ? { id: requestedId } : {}),
    },
  });

  if (!committee) {
    return new Response(
      `data: ${JSON.stringify({ type: 'text', text: 'No active committees currently need checking.' })}\n\ndata: ${JSON.stringify({ type: 'done' })}\n\n`,
      { headers: { 'Content-Type': 'text/event-stream' } },
    );
  }

  let upstream: Response;
  try {
    upstream = await fetch(`${baseUrl.replace(/\/$/, '')}/api/run/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-internal-secret': process.env.INTERNAL_AGENT_SECRET ?? '',
      },
      body: JSON.stringify({
        committeeId: committee.id,
        committeeName: committee.name,
        currentCycle: committee.currentCycle,
        totalCycles: committee.totalCycles,
      }),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Could not reach the agent service.';
    return new Response(
      `data: ${JSON.stringify({ type: 'error', text: message })}\n\ndata: ${JSON.stringify({ type: 'done' })}\n\n`,
      { headers: { 'Content-Type': 'text/event-stream' } },
    );
  }

  if (!upstream.ok || !upstream.body) {
    return new Response(
      `data: ${JSON.stringify({ type: 'error', text: `agent-service returned HTTP ${upstream.status}` })}\n\ndata: ${JSON.stringify({ type: 'done' })}\n\n`,
      { headers: { 'Content-Type': 'text/event-stream' } },
    );
  }

  // Straight passthrough of the upstream SSE body — no re-encoding, so
  // nothing shown to the user is generated by this proxy layer.
  return new Response(upstream.body, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
    },
  });
}
